In [1]:
import numpy as np
import pandas as pd



import os
import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

    
from ice_hold.inmates import county

/Users/owner/projects/python_envs/oscn/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/Users/owner/projects/python_envs/oscn/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [ ]:


inmates = county.inmate_generator()

In [ ]:
inmate = next(inmates)

print(inmate['arrest']['Arrest Date'])

## create dataframe

In [2]:
inmates = county.inmate_generator()

columns = ['id',
           'BookingDate',
           'ArrestDate',
           'ArrestedBy',
           'ReleaseDate',
           'Race',
           'Height',
           'Weight',
           'CountCharges',
           'Charges',
          ]

def inmate_data(i): 
    return [i['Booking ID'],
            i['Booking Date'],
            i['arrest']['Arrest Date'],
            i['arrest']['Arrested By'],
            i['arrest']['Release Date'],
            i['features']['Race'],
            i['features']['Height'],
            i['features']['Weight'],
            len(i['charges']),
            i['charges'],
           ]
    

%time  all_inmates = pd.DataFrame([inmate_data(i) for i in inmates], columns = columns)

all_inmates.head()

CPU times: user 37.4 s, sys: 902 ms, total: 38.3 s
Wall time: 2min 15s

/Users/owner/projects/python_envs/oscn/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: generator 'inmate_generator' raised StopIteration
  """Entry point for launching an IPython kernel.

,id,BookingDate,ArrestDate,ArrestedBy,ReleaseDate,Race,Height,Weight,CountCharges,Charges
0,20190128071,1/28/2019,,/,,H,"5' 09""",140,0,[]
1,20190128070,1/28/2019,1/28/2019,TCSO / COLBERT,,H,"5' 07""",160,1,"[{'Description': 'HOLD/ICE', 'Case #': '', 'Co..."
2,20190128069,1/28/2019,1/28/2019,TCSO / COLBERT,,H,"5' 06""",150,1,"[{'Description': 'HOLD/ICE', 'Case #': '', 'Co..."
3,20190128068,1/28/2019,1/28/2019,TPD / REID,,B,"5' 09""",140,3,[{'Description': 'STOLEN PROPERTY (KCSP) AFCF'...
4,20190128067,1/28/2019,1/28/2019,TPD / RANGEL,,W,"5' 07""",170,3,[{'Description': 'POSS CD SCHED I II 1ST OFFEN...

In [9]:
all_inmates.groupby('ArrestedBy').count()

,id,BookingDate,ArrestDate,ReleaseDate,Race,Height,Weight,CountCharges,Charges
ArrestedBy,,,,,,,,,
,2,2,2,2,2,2,2,2,2
/,3,3,3,3,3,3,3,3,3
/ PATTERSON,1,1,1,1,1,1,1,1,1
/ WARREN,2,2,2,2,2,2,2,2,2
BIXB / ALLEN,1,1,1,1,1,1,1,1,1
BIXB / BURNS,1,1,1,1,1,1,1,1,1
BIXB / DISCH,1,1,1,1,1,1,1,1,1
BIXB / HENDERSON,1,1,1,1,1,1,1,1,1
BIXB / LITTLE,1,1,1,1,1,1,1,1,1
BIXB / PARENTEAU,1,1,1,1,1,1,1,1,1
BIXB / PARTENTEAU,1,1,1,1,1,1,1,1,1
BIXB / WALSH,1,1,1,1,1,1,1,1,1
BROK / B.TAYLOR,1,1,1,1,1,1,1,1,1
BROK / BASKINS,2,2,2,2,2,2,2,2,2
BROK / BROCE,1,1,1,1,1,1,1,1,1
BROK / BUHLER,2,2,2,2,2,2,2,2,2
BROK / BURDEN,1,1,1,1,1,1,1,1,1
BROK / CHISUM,2,2,2,2,2,2,2,2,2
BROK / COOK,1,1,1,1,1,1,1,1,1
BROK / CRAWFORD,1,1,1,1,1,1,1,1,1
BROK / DANIELS,1,1,1,1,1,1,1,1,1
BROK / DUSSLING,1,1,1,1,1,1,1,1,1
BROK / FISHER,5,5,5,5,5,5,5,5,5
BROK / GERAS,1,1,1,1,1,1,1,1,1
BROK / JAMES,1,1,1,1,1,1,1,1,1
BROK / JESSIE,2,2,2,2,2,2,2,2,2
BROK / JOHNSON,1,1,1,1,1,1,1,1,1
BROK / JORDAN,1,1,1,1,1,1,1,1,1
BROK / KOLAR,1,1,1,1,1,1,1,1,1
BROK / LAUDERDALE,5,5,5,5,5,5,5,5,5
...,...,...,...,...,...,...,...,...,...
TPD / VILLA,3,3,3,3,3,3,3,3,3
TPD / VILLAREAL,1,1,1,1,1,1,1,1,1
TPD / VILLARREAL,5,5,5,5,5,5,5,5,5
TPD / VIRGEN,2,2,2,2,2,2,2,2,2
TPD / VIRGIN,1,1,1,1,1,1,1,1,1
TPD / WAGES,1,1,1,1,1,1,1,1,1
TPD / WALKER,1,1,1,1,1,1,1,1,1
TPD / WALL,2,2,2,2,2,2,2,2,2
TPD / WARD,7,7,7,7,7,7,7,7,7
TPD / WARNE,3,3,3,3,3,3,3,3,3
TPD / WARREN,1,1,1,1,1,1,1,1,1
TPD / WATKINS,4,4,4,4,4,4,4,4,4
TPD / WEAVER,2,2,2,2,2,2,2,2,2
TPD / WEBER,6,6,6,6,6,6,6,6,6
TPD / WESTCOTT,1,1,1,1,1,1,1,1,1
TPD / WHALEY,1,1,1,1,1,1,1,1,1
TPD / WHEELER,1,1,1,1,1,1,1,1,1
TPD / WIGGS,1,1,1,1,1,1,1,1,1
TPD / WILCOX,4,4,4,4,4,4,4,4,4
TPD / WILLIAMS,4,4,4,4,4,4,4,4,4
TPD / WOLFE,2,2,2,2,2,2,2,2,2
TPD / WOODARD,1,1,1,1,1,1,1,1,1
TPD / XIONG,1,1,1,1,1,1,1,1,1
TPD / YOST,3,3,3,3,3,3,3,3,3
TPD / ZAFERES,3,3,3,3,3,3,3,3,3
TPD / ZENONI,1,1,1,1,1,1,1,1,1
TPD / ZUNIGA,6,6,6,6,6,6,6,6,6
USM / FOSTER,1,1,1,1,1,1,1,1,1
USM / REED,2,2,2,2,2,2,2,2,2
USM / SPEAKS,1,1,1,1,1,1,1,1,1

## Clean up

In [ ]:
# convert null hold to str 

def safe_hold(hold_val):
    return hold_val if not pd.isna(hold_val) else "No hold"

all_inmates['Hold'] = all_inmates['Hold'].apply(safe_hold)

all_inmates.groupby('Hold').count()

In [ ]:
# fix null charge str

def safe_charge(chg_val):
    return chg_val if not pd.isna(chg_val) else "No charge listed"

all_inmates['Charge'] = all_inmates['Charge'].apply(safe_charge)

all_inmates.groupby('Charge').count()

# safety check for null names

def safe_name(name_str):
    return name_str if not pd.isna(name_str) else "Not_entered"


all_inmates['FirstName'] = all_inmates['FirstName'].apply(safe_name)
all_inmates['LastName'] = all_inmates['LastName'].apply(safe_name)

In [ ]:
# sort by Booking date so that last booking is best record
sorted_inmates = all_inmates.sort_values('BookingDate')
sorted_inmates

In [ ]:
from elasticsearch import Elasticsearch
from elasticsearch import helpers
es = Elasticsearch(http_compress=True)

keys = ['FirstName', 'LastName', 'id', 'Gender', 'BookingDate', 'Hold', 'ReleaseDate', 'Race', 'Charge', 'Jail']


def filterKeys(doc):
    return {k: doc[k] for k in keys }

def doc_generator(df):
    df_iter = df.iterrows()
    for idx, document in df_iter:
        yield {
                "_index": 'inmates',
                "_type": "_doc",
                "_id" : f"{document['id']}",
                "_source": filterKeys(document),
            }
    raise StopIteration

helpers.bulk(es, doc_generator(sorted_inmates))